# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/bookstore" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/config/fromtoml" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/discovery/consul" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/gateway" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/http/cors" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/http/download" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/http/group" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/http/jwt" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/http/static" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/http/timeout" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/http/upload" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/http/withtimeout" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/logx/fileconsole" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/logx/filterfields" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/logx/logrus" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/logx/tokafka" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/logx/zaplog" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/logx/zerolog" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/monolithic" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/rpc/tls/shorturl" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/servicegroup" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/shorturl" # Location of package manifests
    schedule:
      interval: "daily"
